url: "http://chrismastel.ca.s3-website-us-east-1.amazonaws.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Chris Mastel" # the name of your site, e.g. ACME Corp.
